version: '3.8'

services:
  mrpd:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PASSWORD=changeme
      - PORT=8000
    volumes:
      - developer-home:/home/developer
    restart: unless-stopped

volumes:
  developer-home: