version: '3.8'

services:
  codeserver:
    build: .
    container_name: mrpd
    ports:
      - "8080:8080"
    volumes:
      - workspace:/workspace
      - vscode-data:/home/developer/.local/share/code-server
      - git-config:/home/developer/.config/git
      - gh-config:/home/developer/.config/gh
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - ~/.ssh:/home/developer/.ssh:ro
    environment:
      - PASSWORD=${PASSWORD:-changeme}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped

volumes:
  workspace:
  vscode-data:
  git-config:
  gh-config: