version: '3.8'

services:
  mrpd:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=changeme
      - PORT=8080
      # Optional: Add your API keys for development
      # - GITHUB_TOKEN=your_github_token
      # - ANTHROPIC_API_KEY=your_claude_api_key
      # - GIT_USER_NAME=Your Name
      # - GIT_USER_EMAIL=your.email@example.com
    volumes:
      - developer-home:/home/developer
    restart: unless-stopped

volumes:
  developer-home: