version: '3.8'

services:
  codeserver:
    build: .
    container_name: mrpd
    ports:
      - "8080:8080"
    volumes:
      - workspace:/workspace
      - vscode-config:/home/developer/.config/code-server
      - vscode-local:/home/developer/.local/share/code-server
      - ~/.gitconfig:/home/developer/.gitconfig:ro
    environment:
      - PASSWORD=${PASSWORD:-changeme}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped

volumes:
  workspace:
  vscode-config:
  vscode-local: